[package]
name = "audio_lib"
version = "0.1.0"
authors = ["ferris <yupferris@gmail.com>"]

[lib]
name = "audio_lib"
crate-type = ["staticlib"]

[dependencies]
audrey = "0.1.0"
cpal = "0.4.4"
futures = "0.1.1"
libc = "0.2.7"