package;

@:enum abstract SampleId(Int) {
  var SAMPLE_ID_ENEMY_DIALOGUE_HIGH_1 = 0;
  var SAMPLE_ID_ENEMY_DIALOGUE_HIGH_2 = 1;
  var SAMPLE_ID_ENEMY_DIALOGUE_HIGH_3 = 2;
  var SAMPLE_ID_ENEMY_DIALOGUE_HIGH_4 = 3;
  var SAMPLE_ID_ENEMY_DIALOGUE_HIGH_5 = 4;
  var SAMPLE_ID_ENEMY_DIALOGUE_HIGH_6 = 5;
  var SAMPLE_ID_ENEMY_DIALOGUE_LOW_1 = 6;
  var SAMPLE_ID_ENEMY_DIALOGUE_LOW_2 = 7;
  var SAMPLE_ID_ENEMY_DIALOGUE_LOW_3 = 8;
  var SAMPLE_ID_ENEMY_DIALOGUE_LOW_4 = 9;
  var SAMPLE_ID_ENEMY_DIALOGUE_LOW_5 = 10;
  var SAMPLE_ID_ENEMY_DIALOGUE_LOW_6 = 11;
  var SAMPLE_ID_EXPLOSION_1 = 12;
  var SAMPLE_ID_EXPLOSION_2 = 13;
  var SAMPLE_ID_EXPLOSION_3 = 14;
  var SAMPLE_ID_SONAR = 15;
  var SAMPLE_ID_SONAR_ECHO = 16;
  var SAMPLE_ID_TURRET_FIRE = 17;
}